theme: jekyll-theme-minimal
title: Michelle Chiu
email: michelle.chiu108@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  BA in Cognitive Neuroscience, MA in Human Development & Family Studies
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mchiu91.github.io" # the base hostname & protocol for your site
# github_username: mchiu91
# twitter_username:  leanmeanmishine

# Build settings
markdown: kramdown
